### PR TITLE
Hooks + Handle phone rotation/inherit child styling

### PR DESCRIPTION
**Pull request by damau**
Hi,

So first thanks for creating this repo, it's simple and works.  Apologies for the size of this PR.  If you want to reject it off hand based on that, no harm no foul, I can still use this personally.

So this does the following:
1. Adds hooks model
2. Handle screen rotation, so when the screen rotates the widths update and then the drawer open and closes to reflect the width changes.
3. Drawer continues to have an absolute position, while the 'main' section, or it's children keep their styling.  So the main content is no longer absolute, Animation handles moving it.  I did this because I found on rotation all my styles would go past the screen.
4. I also removed the SafeAreaView and iOS logic.  This is because now that the main section (non drawerContext()) inherits what ever is added this means the user styles as normal.

e.g
```react-native
const App: () => Node = () => {
  return (
    <SafeAreaView style={styles.safeArea}>
      <MenuDrawer ...>
          {children} // these are now in the safe area
      </MenuDrawer>
    </SafeAreaView>
   )
}
```

Potential remaining issues:
1. Option to have a different portrait and landscape %
2. drawerContext() does not respect SafeAreaView (main content does).  In general for now the client/user could handle this.  I personally don't see it as a huge issue as it's reasonably easy to just pad it a little.  I wasn't able to add useSafeAreaContext from 'react-native-safe-area-context' to automatically give the drawer an inset.  Though if this get's merged then I might give it another go.

I am a developer, but I haven't doing react for very long.  So there may be some serious faux pas in the code base.  Also there's no particular reason I made it a function, though seems that is where React is going.  This was sort of a mad flow session just trying to get it to do what I wanted.

Really appreciate it if you would take a look, though again given it's a re-write I won't take offence if you say you don't have time.

Thanks
Adam

### CODE REVIEW

**Comment by damau** [comment]
I see I am being hounded :), there is a git hook in the code base to remove semi colons.  Let me know what you would like me to do with this.

**Comment by damau** [comment]
Sorry to nag, please let me know if you are looking into this or not.  No timeline or anything, just if you are still maintaining this repo.  Appreciate as a maintainer it's tricky work life balance but if you let me know that you aren't interested/aren't maintaining I'll move on.

**Comment by pedreviljoen** [comment]
> Sorry to nag, please let me know if you are looking into this or not. No timeline or anything, just if you are still maintaining this repo. Appreciate as a maintainer it's tricky work life balance but if you let me know that you aren't interested/aren't maintaining I'll move on.

Looking into this, thanks for the PR 👍

**Comment by pedreviljoen** [comment]
@damau 
Looks good as far as I can tell... I haven't tested the changes though... 🤔 , do you perhaps have a screenshot or two I can just reference?

Also with the removal of the `SafeAreaView` do you mind just updating the docs to state the change and benefits thereof.

Once you make the updates to the ReadME and just one screenshot that I know it functions, I'll merge it in 👍

**Comment by damau** [comment]
Ah nice one thanks.  Might take me a while to sort as it's the weekend.  I will try to finish it today but expect 1-2 days!

**Comment by damau** [comment]
@pedreviljoen I added a gif and an example with safeareacontext (plus a gif for each overlay and position).  I updated the README.

I also found a few issues with overlay=false + pos=right (I wasn't using it) so tried to clear them up as well. 

I plugged this into my app without all the SafeAreaView stuff from the example and seems to be fine.

NOT tested on Android.

**Comment by damau** [comment]
Hey there a few problems with this on Android, especially with overlay=false.  I will take a bit more time with this and then re-open the PR when I think it's good enough. (circa 2 weeks - 1 month).

Sorry if I wasted your time.

**Comment by damau** [comment]
@pedreviljoen Hey.  I've tried this on a physical android and iOS device.  Appears to be okay.  I will leave it with you now.

**Comment by damau** [comment]
@pedreviljoen just a poke as it's the new year.

**Comment by shobhitsinghal624** [comment]
+1 on this PR
@pedreviljoen would you be able to merge this soon?

**Comment by damau** [comment]
@shobhitsinghal624  thanks.  Have you tried this branch at all? If so which env? Any problems?

**Comment by pedreviljoen** [comment]
@damau 
Is this stable on Android?

**Comment by pedreviljoen** [comment]
@damau 
Please can we remove the `example` directory, it will unnecessarily bloat the size of the package when installing.

Thanks for the `gif` showcasing the functionality, will approve and merge once the `example` directory is removed 😄 

Thanks again 👏

**Comment by damau** [comment]
@pedreviljoen 

Thanks for looking into all this.

In terms of stability iOS/Android I am not using this except in dev on Android and iOS.  Generally I clean up Android after stints on iOS.  It works on both dev envs but beyond that I am not guaranteeing anything.  Noob(ish) react-native dev.

I will likely be developing with it part of the app I am building for a while, so if I see a problem then at least I will likely raise a PR.

Could maybe even say that I will clean it up properly in a month or so. ( 0 guarantee on that though, just if I get very bored)

I added .npmignore.  (except the example/README as npm forces READMEs). Means the example should be excluded from the tar:

```
projects/temp$  npm publish ../react-native-menu --dry-run
npm notice
npm notice 📦  react-native-side-drawer@2.0.0
npm notice === Tarball Contents ===
npm notice 1.2kB .circleci/config.yml
npm notice 834B  .github/ISSUE_TEMPLATE/bug_report.md
npm notice 595B  .github/ISSUE_TEMPLATE/feature_request.md
npm notice 344B  CONTRIBUTING.md
npm notice 1.1kB LICENSE
npm notice 6.0kB README.md
npm notice 4.2MB assets/NonOverlayLeft.gif
npm notice 3.4MB assets/NonOverlayRight.gif
npm notice 3.0MB assets/OverlayLeft.gif
npm notice 3.2MB assets/OverlayRight.gif
npm notice 453B  example/README.md
npm notice 1.5kB index.d.ts
npm notice 4.9kB index.js
npm notice 1.1kB package.json
npm notice === Tarball Details ===
npm notice name:          react-native-side-drawer
npm notice version:       2.0.0
npm notice filename:      react-native-side-drawer-2.0.0.tgz
npm notice package size:  13.7 MB
npm notice unpacked size: 13.9 MB
npm notice shasum:        836582c49ff88992c0dc5526a7f0f60613a99bba
npm notice integrity:     sha512-dQGRgkgtM3ITt[...]Halhxgm1K3ScQ==
npm notice total files:   14
npm notice
+ react-native-side-drawer@2.0.0
```

**Review by pedreviljoen — APPROVED** [review]

**Comment by pedreviljoen** [comment]
Thanks @damau 

Let's see how it goes 🚀

**Comment by damau** [comment]
Thanks for looking into it @pedreviljoen and merging! Will pull the package in later today see how it goes.

**Pull request merged**
